In [1]:
import numpy as np

In [2]:

a=np.matrix("1,2 ; 3 4")
b=np.matrix([[10,20],[30,40]])
print("Matrix a is")
print(a)
print("Matrix b is")
print(b)


Matrix a is
[[1 2]
 [3 4]]
Matrix b is
[[10 20]
 [30 40]]


In [3]:
# 1.	Write a Python Program to Add Two Matrices?

print("Addition of  a and b  matrices is :-")
print(a+b)

Addition of  a and b  matrices is :-
[[11 22]
 [33 44]]


In [4]:
# 2.	Write a Python Program to Multiply Two Matrices?

print("Multiplicaton  of  a and b  matrices is :-")
print(a*b)

Multiplicaton  of  a and b  matrices is :-
[[ 70 100]
 [150 220]]


In [5]:
# 3.	Write a Python Program to Transpose a Matrix?

print(f"Transpose of matrix a is")
print(a.T)


Transpose of matrix a is
[[1 3]
 [2 4]]


In [6]:
# 4.	Write a Python Program to Sort Words in Alphabetic Order?

words=["sagar","sudhir",'samar','shruti','sanjana','sham']
print(sorted(words))

['sagar', 'samar', 'sanjana', 'sham', 'shruti', 'sudhir']


In [8]:
# 5.	Write a Python Program to Remove Punctuation From a String?

punct='''!()-[]{};:'"\,<>./?@#$%^&*_'''
my_str="hello !!! , he asked for tea ---- and went out."
no_punct=''
for char in my_str:
    if char not in punct:
        no_punct+= char
print("my string with punctuation marks is as:-",my_str)
print()
        
print("my_string withount punctuation marks is as:-",no_punct)


my string with punctuation marks is as:- hello !!! , he asked for tea ---- and went out.

my_string withount punctuation marks is as:- hello   he asked for tea  and went out
