In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6]])
b=np.arange(10,70,10).reshape(2,3)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
# 1.	Write a Python Program to find sum of array?

print("sum of array is ")
print(a+b)

sum of array is 
[[11 22 33]
 [44 55 66]]


In [6]:
# 2.	Write a Python Program to find largest element in an array?


print("To find the largest number from array a and b are.")
print("largest from array a is:-",np.max(a))
print("largest from array b is:-",np.max(b))

To find the largest number from array a and b are.
largest from array a is:- 6
largest from array b is:- 60


In [7]:
# 3.	Write a Python Program for array rotation?

print("for array rotation")
print(np.reshape(b,(3,2),order='F'))
print(b.T.reshape(2,3))

for array rotation
[[10 50]
 [40 30]
 [20 60]]
[[10 40 20]
 [50 30 60]]


In [8]:
# 4.	Write a Python Program to Split the array and add the first part to the end?


print("Array a before splitting")
print(a)
arr=np.vsplit(a,2)
arr2=np.concatenate((arr[1],arr[0]),axis=0)
print()
print("Array after splitting and joing")
print(arr2)

Array a before splitting
[[1 2 3]
 [4 5 6]]

Array after splitting and joing
[[4 5 6]
 [1 2 3]]


In [9]:
# 5.	Write a Python Program to check if given array is Monotonic?


def ismonotonic(x):
    return (all(x[i]<=x[i+1] for i in range(len(x)-1)) or all(x[i]>=x[i+1] for i in range(len(x)-1)))
x=[1,2,3,4,5]
print(ismonotonic(x))


True
